### ISSUE TITLE
Consistent UI contact section

### ISSUE THREAD

**Issue by Jaspreet099** [KiranAminPanjwani/MedStats#80] opened 2023-10-14 17:11 UTC
### 🎇 Description

Hey @KiranAminPanjwani Hope you're doing well!

I saw this inconsistent issue in contact section form
- all input fields' and button border-radius should be the same
- Button text should be white on hover, we can add a drop shadow to make it elevate 

Please Assign this issue to me, Thanks!

### 🖼 Screenshots

![image](https://github.com/KiranAminPanjwani/MedStats/assets/75212002/a3f8043d-bcb2-4647-b6d4-38cb06a108ce)

**Comment by KiranAminPanjwani** [comment] 2023-10-14 18:06
Please proceed✨

**Comment by MrDBC** [comment] 2023-10-14 19:04
@Jaspreet099 its more of an #enhancement , rather than a #bug i guess.

**Comment by KiranAminPanjwani** [comment] 2023-10-15 07:34
> @Jaspreet099 its more of an #enhancement , rather than a #bug i guess.

Bug: To address issues or errors in existing content.
Enhancement: To introduce new features or functionalities.

**Comment by Jaspreet099** [comment] 2023-10-15 07:48
Yes @MrDBC it should be under enhancement, but I didn't find it while raising the issue

Thanks @KiranAminPanjwani for assigning this issue to me, but why did `@aryan1982` raise the PR even though he didn't assign this issue 🙂

**Comment by MrDBC** [comment] 2023-10-15 07:57
thanks for the info @KiranAminPanjwani 
learnt something new

**Comment by MrDBC** [comment] 2023-10-15 07:57
> Yes @MrDBC it should be under enhancement, but I didn't find it while raising the issue
> 
> Thanks @KiranAminPanjwani for assigning this issue to me, but why did `@aryan1982` raise the PR even though he didn't assign this issue 🙂


no no, you gave the right tag

**Comment by Aryan1982** [comment] 2023-10-15 08:00
@Jaspreet099 My intention was to address the issue promptly and offer a solution, but I'll ensure that we coordinate effectively moving forward. Let's work together to ensure the issue is resolved efficiently and to the project's benefit.

**Comment by Jaspreet099** [comment] 2023-10-15 08:05
but @Aryan1982, this is not good practice to directly raise PR, if you want to provide a solution you should ask the maintainer first that assign this issue to me.

**Comment by KiranAminPanjwani** [comment] 2023-10-15 08:55
@Jaspreet099 Please work on resolving this issue as quickly as you can, and aim to have it completed by today.

**Closed** 2023-10-15 15:21 UTC
Labels: bug, good first issue, Hacktoberfest'23

**Comment by MrDBC** [comment] 2023-10-15 15:28
great work guys @Jaspreet099 @Aryan1982
